#include "Random.h"
#include "setupTests.h"

// This module tests beamlines with randomness.
// As it's hard to check strict properties for a randomly generated output, we choose a fixed seed approach.
//
// in this module tests mostly compare rayx's output with an older "correct" output from rayx, which was manually checked by a physicist.
//
// Whenever something in the randomness changes, the test will fail and needs to be manually reevaluated.
// In that case, also the corresponding .csv file needs to be updated.
// Note: This .csv file can simply be generated by calling rayx with `-i input/<test>_seeded.rml -c -f`
//
// Additionally to randomness tests, there can also be (non-randomized) regression tests in this module.
// Which compares the current rayx the output of a previous rayx output which we deemed correct.

// Test if something in our random engine changed
TEST_F(TestSuite, randomNumbers) {
    auto rand = [] { return randomDouble(); };
    CHECK_EQ(rand(), 0.34984491052813416);
    CHECK_EQ(rand(), 0.44071569543181971);
    CHECK_EQ(rand(), 0.99076183046509925);
    CHECK_EQ(rand(), 0.66844193307846234);
}

// Test if something in our random engine changed
TEST_F(TestSuite, randomNumbers_normal) {
    auto rand = [] { return randomNormal(0, 1); };
    CHECK_EQ(rand(), -1.3499299374111375);
    CHECK_EQ(rand(), -0.35271630150395944);
    CHECK_EQ(rand(), 1.0403767208244048);
    CHECK_EQ(rand(), 0.42837209461852843);
}

TEST_F(TestSuite, PointSource_seeded) { compareAgainstCorrect("PointSource_seeded"); }

// Tests sourceDepth of MatrixSource.
TEST_F(TestSuite, MatrixSource_seeded) { compareAgainstCorrect("MatrixSource_seeded"); }

// TODO(Sven): verify this test, using seeded results from before efficiency rework
// // Tests reflectivity of materials of a PlaneMirror.
// TEST_F(TestSuite, PlaneMirror_refl_seeded) { compareAgainstCorrect("PlaneMirror_refl_seeded"); }

// Tests the Energy Distribution of a MatrixSource.
TEST_F(TestSuite, MatrixSource_distr_seeded) { compareAgainstCorrect("MatrixSource_distr_seeded"); }

TEST_F(TestSuite, slit1_seeded) { compareAgainstCorrect("slit1_seeded"); }
TEST_F(TestSuite, slit2_seeded) { compareAgainstCorrect("slit2_seeded"); }
TEST_F(TestSuite, slit3_seeded) { compareAgainstCorrect("slit3_seeded"); }
TEST_F(TestSuite, slit4_seeded) { compareAgainstCorrect("slit4_seeded"); }
