#include "setupTests.h"

// This module tests beamlines with randomness.
// As it's hard to check strict properties for a randomly generated output, we choose a fixed seed approach.
//
// in this module tests mostly compare RAY-X's output with an older "correct" output from RAY-X, which was manually checked by a physicist.
//
// Whenever something in the randomness changes, the test will fail and needs to be manually reevaluated.
// In that case, also the corresponding .csv file needs to be updated.
// Note: This .csv file can simply be generated by calling RAY-X with `-i input/<test>_seeded.rml -c`

TEST_F(TestSuite, PointSource_seeded) { compareAgainstCorrect("PointSource_seeded"); }
