name: testWindows

on:
  push:
    branches:
      - '**'     # Run on all branches
    tags-ignore:
      - 'v*'     # Ignore tag pushes matching 'v*'
  pull_request:
    branches:
      - '**'     # Run for all pull requests

env:
  BUILD_TYPE: Release

jobs:
  build:
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Install hdf5
        run: |
          vcpkg install hdf5 --triplet x64-windows
          vcpkg integrate install
          echo "$env:VCPKG_INSTALLATION_ROOT\installed\x64-windows\bin" >> $GITHUB_PATH
        shell: powershell

      - name: Prepare Vulkan SDK
        uses: humbletim/setup-vulkan-sdk@v1.2.1
        with:
          vulkan-query-version: 1.4.304.1
          vulkan-components: Vulkan-Headers, Vulkan-Loader, SPIRV-Tools, Glslang
          vulkan-use-cache: true

      - name: Setup CUDA Toolkit
        id: cuda-toolkit
        shell: pwsh
        run: .\Scripts\setup-cuda.ps1
        env:
          # if you want to change the cuda version, go to Scripts/setup-cuda-ps1 and add a download link for the new version there.
          INPUT_CUDA_VERSION: 12.9.1

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DRAYX_WERROR=ON -DRAYX_REQUIRE_CUDA=ON -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build
        run: |
          type "${{github.workspace}}/build/CMakeCache.txt"
          echo "D:\a\rayx\rayx\vcpkg\installed\x64-windows\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

      - name: Run
        working-directory: ${{github.workspace}}
        run: |
          $Env:RML="Intern/rayx-core/tests/input/METRIX_U41_G1_H1_318eV_PS_MLearn_v114.rml"
          ./build/bin/release/rayx -x -c -V -i $Env:RML
          ./build/bin/release/rayx -x    -V -i $Env:RML

      - name: Test
        working-directory: ${{github.workspace}}/build/bin/release
        run: ./rayx-core-tst -x

      - name: CPack
        run: |
          cd ${{github.workspace}}/build
          cpack -G ZIP

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: RAYX
          path: ${{github.workspace}}/build/RAYX-*.*.*-win64.zip
